services:
  mysql:
    image: mysql:8.4
    container_name: multipost-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multipost
      MYSQL_USER: multipost
      MYSQL_PASSWORD: multipost
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: multipost-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: multipost-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: multipost
      RABBITMQ_DEFAULT_PASS: multipost
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql-data:
